Player ranged attack
WATOLINK/bci-gaming pull request #49
Opened 2024-03-17 16:36 UTC by gracexuwt

## ClickUp ticket link

[Player Long Range Attack](https://app.clickup.com/t/8685qfv3d)

## Implementation description
Prefab shooting is implemented for player ranged attacks.
Bullet implementation could be found in TemplateProjectile, and impact effect implementation could be found in Temporary Projectile Effect.
The bullet shoots from the direction where the player is facing by using the RangeFirePoint.

## Steps to test
1. Play game and press down on Ctrl button
2. Make sure that the bullet is shot after the player animation is finished, and that the bullet hits the target (either enemy or platform). If there is no obstacle in the direction of the player, then the bullet should "fly" offscreen
3. Make sure that the instantiated bullet and impact effect (the effect when a bullet hits a target) prefabs would be deleted from the hierarchy once the ranged attack is finished.
4. If enemy is hit, ensure that enemy health decreases

## What should reviewers focus on?
Ranged attack mechanics should run smoothly

## Checklist
- [x] My PR name is descriptive
- [x] My commit messages are descriptive. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR
- [x] My code is organized, and commented and documented so that another dev can understand what I did

2024-03-17 23:11 UTC, kimchiloof requested changes
Works well, delay fixed! :)

Just had a few thoughts on code readability, was wondering if these changes make it easier or harder to understand each function's purpose.

2024-03-17 23:11 UTC, kimchiloof commented on bci-game/Assets/Scripts/Entity/Player/PlayerAttackRange.cs
> +        }
Would this be better? Moves the sound effect to occur when the bullet spawns, separates shooting and cooldown more explicitly.

```c#
private IEnumerator Shoot()
{
    canFire = false;
    
    animator.SetTrigger(IsRanged);
    
    // shoot after animation finishes playing
    yield return new WaitForSeconds(animationTime);
    soundController.PlaySound(rangeAttackSounds, rangeAttackVolume);
    Instantiate(rangeProjectile, firePoint.position, transform.localScale.x > 0 ? Quaternion.identity : Quaternion.Euler(0, 180, 0));
    
    StartCoroutine(AttackCooldown(1f / rangeAttackSpeed));
}

private IEnumerator AttackCooldown(float duration)
{
    yield return new WaitForSeconds(duration);
    canFire = true;
}
```

2024-03-17 23:11 UTC, kimchiloof commented on bci-game/Assets/Scripts/Entity/Player/PlayerAttackRange.cs
> +                Shoot();
If making Shoot() to be a Coroutine:
```c#
StartCoroutine(Shoot());
```

2024-03-20 04:08 UTC, gracexuwt commented
Thanks for reviewing! Fixed code readability

On Sun, 17 Mar 2024 at 19:11, Kevin Ge ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Works well, delay fixed! :)
>
> Just had a few thoughts on code readability, was wondering if these
> changes make it easier or harder to understand each function's purpose.
> ------------------------------
>
> In bci-game/Assets/Scripts/Entity/Player/PlayerAttackRange.cs
> <https://github.com/WATOLINK/bci-gaming/pull/49#discussion_r1527636752>:
>
> > +        private void Shoot()
> +        {
> +            soundController.PlaySound(rangeAttackSounds, rangeAttackVolume);
> +            animator.SetTrigger(IsRanged);
> +
> +            canFire = false;
> +            StartCoroutine(Attack(1f / rangeAttackSpeed));
> +        }
> +
> +        private IEnumerator Attack(float duration)
> +        {
> +            yield return new WaitForSeconds(animationTime);
> +            //shoot after animation finishes playing
> +            Instantiate(rangeProjectile, firePoint.position, transform.localScale.x > 0 ? Quaternion.identity : Quaternion.Euler(0, 180, 0));
> +            //attack cooldown
> +            yield return new WaitForSeconds(duration);
> +            canFire = true;
> +        }
>
> Would this be better? Moves the sound effect to occur when the bullet
> spawns, separates shooting and cooldown more explicitly.
>
> private IEnumerator Shoot(){
>     canFire = false;
>
>     animator.SetTrigger(IsRanged);
>
>     // shoot after animation finishes playing
>     yield return new WaitForSeconds(animationTime);
>     soundController.PlaySound(rangeAttackSounds, rangeAttackVolume);
>     Instantiate(rangeProjectile, firePoint.position, transform.localScale.x > 0 ? Quaternion.identity : Quaternion.Euler(0, 180, 0));
>
>     StartCoroutine(AttackCooldown(1f / rangeAttackSpeed));}
> private IEnumerator AttackCooldown(float duration){
>     yield return new WaitForSeconds(duration);
>     canFire = true;}
>
> ------------------------------
>
> In bci-game/Assets/Scripts/Entity/Player/PlayerAttackRange.cs
> <https://github.com/WATOLINK/bci-gaming/pull/49#discussion_r1527636948>:
>
> > +        [SerializeField, Range(0f, 1f)] private float rangeAttackVolume = 0.8f;
> +
> +        private float animationTime = 0.5f;
> +        private static readonly int IsRanged = Animator.StringToHash("isRanged");
> +
> +        private void Awake()
> +        {
> +            animator = GetComponent<Animator>();
> +            soundController = GetComponent<CharacterSoundController>();
> +        }
> +
> +        private void Update()
> +        {
> +            if (Input.GetButton("Fire1") && canFire)
> +            {
> +                Shoot();
>
> If making Shoot() to be a Coroutine:
>
> StartCoroutine(Shoot());
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/WATOLINK/bci-gaming/pull/49#pullrequestreview-1941610044>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWFGQRBIWTQ5FMEEQRSR6CDYYYPLNAVCNFSM6AAAAABE2K4YW6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBRGYYTAMBUGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-20 20:27 UTC, kimchiloof approved these changes

2024-03-20 20:33 UTC, kimchiloof commented
Looks good to me! Will leave it up for a day or two if anyone else wants to have a look before it's merged, but otherwise all good to be merged into main.

2024-03-24 20:01 UTC, merged